---

# Use the first available external network
infra_external_network_id: "5283f642-8bd8-48b6-8608-fa3006ff4539"


# Pick suitable flavors from the available flavors
#   Only consider flavors with at least 2 CPUs and 20GB disk

# For the infra, we need at least 8GB RAM, but 16GB is better, plus at least 4 CPUs
infra_flavor_id: "f120e108-7883-4933-bb76-4f88909447f6"  # l6.c4 (4 vCPU, ~15GB RAM, 75GB disk)
infra_fixed_floatingip: "130.246.80.30"
#####
community_images_custom_properties:
  - "hw_scsi_model=virtio-scsi"
  - "hw_disk_bus=scsi"

capi_cluster_addons_csi_cinder_availability_zone: ceph
azimuth_capi_operator_capi_helm_csi_cinder_default_availability_zone: ceph

# Use the same external network as we use for the infra
azimuth_capi_operator_external_network_id: "{{ infra_external_network_id }}"

# Upload images as private
# CaaS/Kubernetes will only work within the tenancy in which Azimuth is deployed
community_images_default_visibility: private
# However don't assume we are in control of the images, e.g. if there is another
# Azimuth deployment on the same cloud
community_images_update_existing_visibility: false

# Disable HTTPS and certificate verification everywhere to avoid certificate issues
ingress_tls_enabled: false

# Use the same external network as the infra for Azimuth auto-created networking
azimuth_openstack_external_net_template: >-
  {{-
    lookup('pipe', 'openstack network show -f value -c name ' ~ infra_external_network_id)
  }}
# Disable SSL verification for OpenStack in case it uses a custom CA
azimuth_openstack_verify_ssl: false

azimuth_current_cloud_name: AzimuthDev

# Use secrets that are not really secret for ease
# admin_dashboard_ingress_basic_auth_password: admin
harbor_admin_password: admin
harbor_secret_key: abcdefghijklmnop
# keycloak_admin_password: admin
# zenith_registrar_subdomain_token_signing_key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AA
# azimuth_secret_key: 9876543210ZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedcda00
#####
# Configuration of authenticators / authentication methods
#####
# Whether the password authenticator should be enabled (enabled by default)
azimuth_authenticator_password_enabled: true
# The label for the password authenticator
azimuth_authenticator_password_label: "Username + Password"

# Whether the appcred authenticator should be enabled (not enabled by default)
azimuth_authenticator_appcred_enabled: false
# The label for the appcred authenticator
azimuth_authenticator_appcred_label: "Application Credential"


azimuth_authenticator_federated_enabled: yes
azimuth_authenticator_federated_provider: "openid"
azimuth_authenticator_federated_protocol: "openid"

azimuth_openstack_domain: stfc

azimuth_openstack_auth_url: https://openstack.stfc.ac.uk:5000/v3

