---
capi_cluster_fluent_operator_values:
  fluentbit:
    enable: true
    resources:
      limits:
        cpu: 500m
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 25Mi
    annotations:
      fluentbit.io/exclude: "true"
      promtheus.io/scrape: "true"

    input:
      tail:
        enable: true
      systemd:
        enable: true

    output:
      opensearch: "{{ fluent_operator_cluster_opensearch_config }}"
      loki:
        enable: true
        host: loki-stack
        port: 3100
        tenantID: ""
        labels:
          - job=fluent-bit
          - pod=$kubernetes['pod_name']
          - namespace=$kubernetes['namespace_name']
          - container_name=$kubernetes['container_name']
          # - app=$kubernetes['labels']['app'] # This isn't standard (i.e. sometimes its labels.k8s.app); and it generally duplicates container_name anyway
        removeKeys: []
        autoKubernetesLabels: "off" # Only seems to work for labels and annotations, not metadata. Disabling and doing it myself!
        lineFormat: json

      prometheusMetricsExporter:
        metricsExporter:
          host: "0.0.0.0"
          port: 2020
          addLabels:
            app: "fluentbit"

    filter:
      kubernetes:
        enable: true
        labels: true
        annotations: false
      containerd:
        enable: true
      systemd:
        enable: true

    serviceMonitor:
      enable: true
      interval: 30s
      path: /api/v2/metrics/prometheus
      scrapeTimeout: 10s
      port: http-metrics
  fluentd:
    enable: false
