capi_cluster_fluent_operator_values:
  fluentbit:
    enable: true
    resources:
      limits:
        cpu: 500m
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 25Mi
    annotations:
      fluentbit.io/exclude: "true"
      promtheus.io/scrape: "true"

    # additionalVolumes:
    #   - name: host-proc
    #     hostPath:
    #       path: /proc/
    #   - name: host-sys
    #     hostPath:
    #       path: /sys/
    #   - name: host-buffer
    #     hostPath:
    #       path: /tmp/fluent-bit-buffer
    # additionalVolumesMounts:
    #   - mountPath: /host/sys
    #     mountPropagation: HostToContainer
    #     name: host-sys
    #     readOnly: true
    #   - mountPath: /host/proc
    #     mountPropagation: HostToContainer
    #     name: host-proc
    #     readOnly: true
    #   - mountPath: /host/fluent-bit-buffer
    #     mountPropagation: HostToContainer
    #     name: host-buffer

    input:
      tail:
        enable: true
      systemd:
        enable: true
      # nodeExporterMetrics:
      #   tag: node_metrics
      #   scrapeInterval: 15s
      #   path:
      #     procfs: /proc/
      #     sysfs: /sys/
      # fluentBitMetrics:
      #   scrapeInterval: 10s
      #   scrapeOnStart: true
      #   tag: "fb.metrics"

    output:
      opensearch:
        # TODO change this to point to opensearch "olaf" cluster (SCD department cluster)
        host: opensearch.dev-worker.nubes.stfc.ac.uk
        port: 9200
        httpPassword:
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials
              key: password
        httpUser:
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials
              key: username
        logstashFormat: On
        # At the time of writing, custom addons have templating disabled:
        # https://github.com/azimuth-cloud/capi-helm-charts/blob/affae0544b07c4b2e641b3b5bf990e561c055a91/charts/cluster-addons/templates/custom-addons.yaml#L15
        # 1. Temporarily re-enable templating with an endraw
        # 2. Template for Openstack Project ID by base64 decoding the user info from the cloud_credentials secret
        #    a. https://github.com/azimuth-cloud/cluster-api-addon-provider/tree/main?tab=readme-ov-file#templates
        #    b. Note, the "cluster" and "infra_cluster" are CRD types cluster.cluster.x-k8s.io and openstackcluster.infrastructure.cluster.x-k8s.io; not clusters.azimuth.stackhpc.com
        # 3. Template for the Kubernetes UID of the cluster object, for it to be unique to the project
        # 4. Re-disable templating
        logstashPrefix: "{{ '{%- endraw %}' }}{% raw %}kube_logs_azimuth_{{ cluster.metadata.uid }}_projectid_{{ (cloud_identity.data[\"user_info.yaml\"] | b64decode | fromyaml).project_id }}{% endraw %}{{ '{%- raw %}' }}"
        # index: "azimuth_user_logs_<some_unique_name>"
        replaceDots: true
        type: flb_type
        traceError: true
        suppressTypeName: On
        timeKey: "@timestamp"
        tls:
          verify: false
          debug: 1

      loki:
        enable: true
        host: loki-stack
        port: 3100
        tenantID: ""
        labels: ["job=fluent-bit"]
        # removeKeys: ["kubernetes", "stream"]
        removeKeys: []
        autoKubernetesLabels: "on"
        # lineFormat: json

      prometheusMetricsExporter:
        metricsExporter:
          host: "0.0.0.0"
          port: 2020
          addLabels:
            app: "fluentbit"
    # service:
    #   storage:
    #     path: "/host/fluent-bit-buffer/"
    #     backlogMemLimit: "50MB"
    #     checksum: "off"
    #     deleteIrrecoverableChunks: "on"
    #     maxChunksUp: 128
    #     metrics: "on"
    #     sync: normal

    filter:
      kubernetes:
        enable: true
        labels: true
        annotations: false
      containerd:
        enable: true
      systemd:
        enable: true
    
    serviceMonitor:
      enable: true
      interval: 30s
      path: /api/v2/metrics/prometheus
      scrapeTimeout: 10s
      port: http-metrics
  fluentd:
    enable: false