dev_user_cluster_alertmanager_values:
  global:
    resolve_timeout: 1h
    # smtp_smarthost:
    # smtp_from: cloud-support@stfc.ac.uk
    # smtp_require_tls: false
    # Opsgenie Credentials are a WIP. They should be moved to secrets eventually, perhaps per-cluster.
    # opsgenie_api_key: 
    # opsgenie_api_url:

  route:
    # we need a null reciever to workaround azimuth addon enforced defaults 
    # https://github.com/azimuth-cloud/capi-helm-charts/blob/main/charts/cluster-addons/templates/monitoring/kube-prometheus-stack.yaml#L41-L44
    receiver: "null"
    routes:
      - receiver: "default-receiver"
        group_by: ["cluster", "service"]
        group_wait: 30m
        group_interval: 4h
        repeat_interval: 2d
        active_time_intervals:
          - officehours

        # mute watchdog alert
        #   - this should always be firing
        # mute infoinhibitor alert
        #   - not useful by itself
        #   - if this is firing, we're suppressing severity=info alerts
        #   - infoinhibitor rules should be automatically configured
        matchers:
          - alertname !~ "Watchdog|InfoInhibitor" 

  inhibit_rules:
    # mute warning/info alerts on same service if a critical alert is firing - less noise
    - source_matchers:
        - severity = "critical"
      target_matchers:
        - severity = "warning"
      equal: [cluster, service]

  time_intervals:
    - name: officehours
      time_intervals:
        - times:
            - start_time: 07:00
              end_time: 18:00
          weekdays: ["monday:friday"]
          location: "Europe/London"

  receivers:
    - name: "null"
    - name: default-receiver
      # email_configs:
      #   - to: cloud-support@stfc.ac.uk
      #     send_resolved: true
      #     headers:
      #       subject: |
      #         {%- raw %}
      #         "({{ .CommonLabels.env }} : {{ .CommonLabels.cluster }}) {{ or .CommonLabels.alertname "Multiple Alerts" }}"
      #         {%- endraw %}
      #     html: |-
      #       {%- raw %}
      #       <b>You have the following alerts:</b>
      #       {{ range .Alerts }}
      #           <b>{{.Labels.alertname}}</b><br/>
      #           <b>Annotations:</b><br/>
      #           <ul>{{ range .Annotations.SortedPairs }}
      #               <li><strong>{{ .Name }}</strong> = {{ .Value }}</li>
      #           {{ end }}</ul>
      #           <b>Labels:</b>
      #           <ul>{{ range .Labels.SortedPairs }}
      #               <li><strong>{{ .Name }}</strong> = {{ .Value }}</li>
      #           {{ end }}</ul>
      #           <p><a href="{{ .GeneratorURL }}">View in Prometheus</a></p>
      #       {{ end }}
      #       {%- endraw %}
      #     text: |-
      #       {%- raw %}
      #       You have the following alerts:
      #       {{ range .Alerts }}
      #       * [{{ .Labels.severity }}] {{.Labels.alertname}}
      #         Annotations:
      #         {{ range .Annotations.SortedPairs }}
      #         {{ .Name }} = {{ .Value }}
      #         {{ end }}
      #         Labels:
      #         {{ range .Labels.SortedPairs }}
      #         {{ .Name }} = {{ .Value }}
      #         {{ end }}
      #         View in Prometheus: {{ .GeneratorURL }}
      #       {{ end }}
      #       {%- endraw %}
      # opsgenie_configs:
      #  - # https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config
      # Defaults here: https://github.com/prometheus/alertmanager/blob/c653800ffe4af31f4c3f9d81708301f3dd5600fa/template/default.tmpl#L43
      slack_configs:
        - api_url: https://hooks.slack.com/services/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
          channel: 'C098YQLR20M'
          username: 'alertmanager'
          send_resolved: true
          icon_url: https://avatars3.githubusercontent.com/u/3380462
          title: |-
            {%- raw %}
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
            {%- endraw %}
          text: |-
            {%- raw %}
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

            *Description:* {{ .Annotations.description }}

            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
            {%- endraw %}

  templates:
    - "/etc/alertmanager/config/*.tmpl"