---
# variables for setting up singlenode dev azimuth 

capi_cluster_addons_ingress_load_balancer_ip: < FIP 1 >
zenith_sshd_service_load_balancer_ip: < FIP 2 >
infra_fixed_floatingip: < FIP 3 >

infra_flavor_id: "81b72052-9bee-4917-a4d9-05d3e7d0f671" # l3.tiny (8 vCPU, ~30GB RAM, 200GB disk)
# Disable HTTPS and certificate verification everywhere to avoid certificate issues
ingress_tls_enabled: false
# Disable SSL verification for OpenStack in case it uses a custom CA
azimuth_openstack_verify_ssl: false

# Upload images as private - since its development - only the project its built on can spawn test VMs/clusters 
community_images_default_visibility: private
community_images_update_existing_visibility: true

# Set user cluster control plane count to 1 on dev, reduce quota requirement
azimuth_capi_operator_capi_helm_control_plane_count: 1

# deny creation of any platforms on any tenancies other than what is listed
# prevents unauthorized users using azimuth dev instances - as its meant for developing features and testing things 
platforms_tenancy_allow_list: < project ID >

#Disable workstation deployment
azimuth_clusters_enabled: false

#Disables pulling community images, remove line to pull images
community_images: {}

# Disable opensearch output on dev instances
fluent_operator_user_opensearch_config: {}
user_cluster_logging_user: 
user_cluster_logging_pass: 

#############################################################################
# Azimuth configuration

# The name of the current cloud
azimuth_current_cloud_name: dev-stfc-cloud
# The label for the current cloud
azimuth_current_cloud_label: Development STFC Cloud