#####
# This file contains environment-specific secrets for a CAPI mgmt cluster
# deployment
#
# It should be encrypted if stored in version control
#####

# The Slack webhook URL for monitoring alerts (optional)
# checkov:skip=CKV_SECRET_14:Prevent CHECKOV linting from flagging an exposed secret
# alertmanager_config_slack_webhook_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX # gitleaks:allow
