---
name: Pull Request Testing

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  id-token: write

on:
  # Allow manual execution on any branch
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty. "
    inputs:
      target-cloud:
        description: >-
          The cloud to target for the run.
          Leave blank to use the default cloud.
        type: choice
        options:
          - ""
          - arcus
          - leafcloud

  # Execute by default on pull requests to the devel branch
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - devel

# Use the head ref for workflow concurrency, with cancellation
# This should mean that any previous runs of this workflow for the same PR
# are cancelled when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    name: Fail on Remote
    runs-on: ubuntu-latest
    steps:
      - name: Code under test must be from a branch in the azimuth-config repo
        run: |
          if [ "${{ github.repository }}" != "azimuth-cloud/azimuth-config" ]; then
            exit 1
          fi

  lint:
    name: Lint
    needs: [fail_on_remote]
    uses: ./.github/workflows/lint.yml

  files_changed:
    name: Detect Files Changed
    needs: [fail_on_remote, lint]
    runs-on: ubuntu-latest
    # Map a step output to a job output, this allows other jobs to be gated on the filter results
    outputs:
        paths: ${{ steps.filter.outputs.paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Paths Filter
        # For safety using commit of dorny/paths-filter@v3
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            paths:
              - .gitignore
              - .gitattributes
              - .github/actions/**
              - .github/environments/common
              - .github/environments/arcus
              - .github/environments/leafcloud
              - .github/workflows/pr.yml
              - .github/workflows/test-singlenode.yml
              - bin/activate
              - bin/check-alerts
              - bin/create-debug-bundle
              - bin/ensure-venv
              - bin/generate-secrets
              - bin/kube-connect
              - bin/run-tests
              - bin/seed-ssh
              - environments/base/**
              - environments/singlenode/**
              - environments/demo/**
              - requirements.txt
              - requirements.yml

  run_azimuth_tests:
    # Use the output of the above filter to check if the files listed under "paths" have changed.
    # We can negate this check to run an alternative job,
    # we can add additional filters like "paths" and action on those.
    # Example: https://github.com/getsentry/sentry/blob/2ebe01feab863d89aa7564e6d243b6d80c230ddc/.github/workflows/backend.yml#L36
    name: Run Azimuth Tests
    needs: files_changed
    if: needs.files_changed.outputs.paths == 'true'
    uses: ./.github/workflows/test-singlenode.yml
    secrets: inherit
