---
name: Single node test

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  id-token: write

on:
  workflow_call:

  # Allow manual execution on any branch
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty. "
    inputs:
      target-cloud:
        description: >-
          The cloud to target for the run.
          Leave blank to use the default cloud.
        type: choice
        options:
          - ""
          - arcus
          - leafcloud

jobs:
  # Tests a single node deployment
  test_singlenode:
    runs-on: ubuntu-latest
    steps:
      # We need to check out the code under test first in order to use local
      # actions
      - name: Checkout code under test
        uses: actions/checkout@v4

      - name: Set up Azimuth environment
        uses: ./.github/actions/setup
        with:
          os-clouds: ${{ secrets.OS_CLOUDS }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          target-cloud: ${{ inputs.target-cloud || vars.TARGET_CLOUD }}
        # GitHub terminates jobs after 6 hours
        # We don't want jobs to acquire the lock then get timed out before
        # they can finish
        # So wait a maximum of 3 hours to acquire the lock, leaving 3 hours
        # for other tasks in the job
        timeout-minutes: 180

      - name: Provision Azimuth
        uses: ./.github/actions/provision

      - name: Run Azimuth tests
        uses: ./.github/actions/test

      - name: Destroy Azimuth
        uses: ./.github/actions/destroy
        if: ${{ always() }}
